### ISSUE TITLE
Variables with only an upper bound

### ISSUE THREAD

**Issue by ARBaart** [emallson/rplex#1]
On line 334 a `var!` with only an upper bound is turned into a `var!` with `0.0` as its lower bound _but infinity as its upper bound_, not the provided upper bound:
`($name:tt <= $ub:tt -> $obj:tt) => (var!(0.0 <= $name <= INFINITY -> $obj));`

Surely this should be:
`($name:tt <= $ub:tt -> $obj:tt) => (var!(0.0 <= $name <=$ub -> $obj));`

**Comment by emallson** [comment]
Resolved by #2
